name: build
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Run tests
        run: go test -v -covermode=count -coverprofile=profile.cov ./...
      - name: Send coverage report to coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
